name: Deploy project to EBS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Zip Source Code
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r app.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: biostation-lab-pdf-parse
          environment_name: Biostation-lab-pdf-parse-env
          version_label: parse-god-gitaction-deploy-${{ github.run_number }}
          region: us-east-1
          deployment_package: ./app.zip